### ISSUE TITLE
How does this work exactly?

### ISSUE THREAD

**Issue by bwhurd** [Arthur-Milchior/anki-style-around-fields#1]
Hi, I think this addon is exactly what I'm looking for, but not sure how to use it.  Anyway you could give a rough and dirty example?  I'm hoping I can for example, update a card template like this:
Original :   
`{field}`
Updated: 
`<div class="tags">{{Tags}}</div>`

Or am I confused at what this does?  THANKS!

**Comment by bwhurd** [comment]
Sorry, I didn't see that you explained it in github, but not on the addon page at ankiweb.  I figured it out.  Thanks!

**Comment by Arthur-Milchior** [comment]
No trouble

The ankiweb page is quite hard to update, sorry
